DEFAULT_PERMISSIONS = {
    "admin": {
        "product": ["view", "create", "update", "delete", "import", "export"],
        "customer": ["view", "create", "update", "delete", "import", "export"],
        "warehouse": ["view", "create", "update", "delete", "import", "export"],
        "uom": ["view", "create", "update", "delete", "import", "export"],
        "template": ["view", "create", "update", "delete", "print", "import", "export"],
        "order": ["view", "create", "update", "delete", "approve", "confirm", "print"],
        "wms": ["view", "create", "update", "scan", "dispatch", "print", "approve"],
        "document": ["view", "create", "print"],
        "user": ["view", "create", "update", "delete"],
        "permission": ["view", "update"],
        "inventory": ["view", "create", "update", "cycle_count", "approve_count"],
        "reports": ["view", "export"],
        "label": ["view", "generate"],
        "transfer": ["view", "create", "update", "approve", "reject", "complete", "cancel"],
        "entity": ["view", "create", "update", "delete"],
        "price_approval": ["view", "create", "update", "delete", "approve", "reject"],
        "tax_invoice": ["view", "create", "update", "replace", "cancel", "print"],
        "sales_return": ["view", "create", "update", "approve", "reject"],
        "approval": ["view", "approve"],
        "settings": ["view", "manage"],
    },
    "sales": {
        "product": ["view"],
        "customer": ["view", "create", "update"],
        "warehouse": ["view"],
        "uom": ["view"],
        "template": ["view"],
        "order": ["view", "create", "update", "print"],
        "document": ["view", "create", "print"],
        "inventory": ["view"],
        "price_approval": ["view", "create", "update", "delete"],
        "tax_invoice": ["view", "create", "print"],
        "sales_return": ["view", "create", "update"],
    },
    "manager": {
        "product": ["view", "export"],
        "customer": ["view", "create", "update", "export"],
        "warehouse": ["view", "export"],
        "uom": ["view"],
        "template": ["view"],
        "order": ["view", "create", "update", "approve", "confirm", "print"],
        "wms": ["view", "create", "update", "scan", "dispatch", "print", "approve"],
        "document": ["view", "create", "print"],
        "inventory": ["view", "cycle_count", "approve_count"],
        "reports": ["view", "export"],
        "label": ["view", "generate"],
        "transfer": ["view", "create", "approve", "reject", "complete"],
        "entity": ["view"],
        "price_approval": ["view", "create", "update", "approve", "reject"],
        "tax_invoice": ["view", "create", "update", "replace", "cancel", "print"],
        "sales_return": ["view", "create", "update", "approve", "reject"],
        "approval": ["view", "approve"],
        "settings": ["view"],
    },
    "warehouse": {
        "product": ["view"],
        "warehouse": ["view"],
        "uom": ["view"],
        "template": ["view"],
        "order": ["view"],
        "wms": ["view", "create", "update", "scan", "dispatch", "print"],
        "document": ["view", "create", "print"],
        "inventory": ["view", "cycle_count"],
        "label": ["view", "generate"],
        "transfer": ["view", "create", "update"],
    },
}
